import {
  Activity,
  Apple,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  Check,
  ChevronDown,
  Clock,
  Database,
  Download,
  Eye,
  EyeOff,
  FileBarChart,
  FilePlus2,
  FolderOpen,
  LayoutDashboard,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Play,
  Save,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react"

export const icons = {
  brand: Database,
  dashboard: LayoutDashboard,
  dossiers: FolderOpen,
  users: Users,
  reports: BarChart3,
  settings: Settings,
  search: Search,
  notifications: Bell,
  chevronDown: ChevronDown,
  signOut: LogOut,
  newDossier: FilePlus2,
  inviteUser: UserPlus,
  download: Download,
  save: Save,
  report: FileBarChart,
  activity: Activity,
  pendingReviews: Clock,
  trendUp: ArrowUpRight,
  arrowRight: ArrowRight,
  check: Check,
  shield: ShieldCheck,
  lock: LockKeyhole,
  star: Star,
  sparkles: Sparkles,
  menu: Menu,
  close: X,
  apple: Apple,
  play: Play,
  eye: Eye,
  eyeOff: EyeOff,
  arrowLeft: ArrowLeft,
  user: User,
  mail: Mail,
} as const

export type IconName = keyof typeof icons

export function resolveIcon(name: IconName) {
  return icons[name]
}
